-- RNF03: esquema do catálogo (livro, autor, categoria, exemplar), com
-- restrições que reforçam RN01 (ISBN único) e RN02 (patrimônio único).

create table categoria (
    id     bigint generated by default as identity primary key,
    nome   varchar(100) not null unique,
    ativo  boolean      not null default true
);

create table autor (
    id     bigint generated by default as identity primary key,
    nome   varchar(150) not null,
    ativo  boolean      not null default true
);

create table livro (
    id              bigint generated by default as identity primary key,
    isbn            varchar(13)  not null unique,
    titulo          varchar(255) not null,
    editora         varchar(255),
    ano_publicacao  integer,
    categoria_id    bigint       not null references categoria (id),
    ativo           boolean      not null default true
);

create table livro_autor (
    livro_id  bigint not null references livro (id),
    autor_id  bigint not null references autor (id),
    primary key (livro_id, autor_id)
);

create table exemplar (
    id                 bigint generated by default as identity primary key,
    livro_id           bigint      not null references livro (id),
    codigo_patrimonio  varchar(50) not null unique,
    status             varchar(20) not null
        check (status in ('DISPONIVEL', 'EMPRESTADO', 'RESERVADO', 'DANIFICADO', 'EXTRAVIADO')),
    ativo              boolean     not null default true,
    versao             bigint      not null default 0
);

create index idx_livro_titulo on livro (titulo);
create index idx_livro_categoria_id on livro (categoria_id);
create index idx_livro_autor_autor_id on livro_autor (autor_id);
create index idx_exemplar_livro_id on exemplar (livro_id);
